### ISSUE TITLE
ES-Gaussian Added to awesome-Implicit-NeRF-SLAM Repo

### ISSUE THREAD

**Issue by DoongLi** [Dreame-Simulation-Group/ESGaussian#2]
Hi, this message serves as a reminder that your paper ”ES-Gaussian: Gaussian Splatting Mapping via Error Space-Based Gaussian Completion“, has been included in the repository. https://github.com/DoongLi/awesome-Implicit-NeRF-SLAM.
If there is any missing information about your work on this repository (including paper links, code, datasets, website, etc), please let us know or submit a pull request (PR) directly.

**Comment by ericzzj1989** [comment]
Hi @DoongLi,

Thank you for your interest!

**Comment by ericzzj1989** [comment]
Hi @DoongLi,

Thank you for your interest!
